const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.HTMLElement,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pathfinding.Acts.SetAcc,
		C3.Behaviors.Pathfinding.Acts.SetSpeed,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{praca1: 0},
	{calcada: 0},
	{predio: 0},
	{trem2: 0},
	{ExploradorDeRotas: 0},
	{Piscar: 0},
	{Enemy: 0},
	{Mouse: 0},
	{Teclado: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{Hero: 0},
	{Casa1: 0},
	{grama: 0},
	{rua2: 0},
	{rua3: 0},
	{neve1: 0},
	{neve2: 0},
	{neve3: 0},
	{neve4: 0},
	{deserto1: 0},
	{deserto2: 0},
	{Sprite21: 0},
	{rua: 0},
	{calcada1: 0},
	{pego: 0},
	{Senóide: 0},
	{Âncora: 0},
	{garrafa2: 0},
	{salgadinho2: 0},
	{latinha2: 0},
	{calcada2: 0},
	{pedra1: 0},
	{pedra2: 0},
	{poste1: 0},
	{pedra4: 0},
	{arvore1: 0},
	{arvore2: 0},
	{correio: 0},
	{poste2: 0},
	{pedra5: 0},
	{arvore3: 0},
	{arvore4: 0},
	{pedra6: 0},
	{pedra7: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{casa2: 0},
	{casa3: 0},
	{casa4: 0},
	{muro2: 0},
	{muro1: 0},
	{rua1: 0},
	{pedra8: 0},
	{planta: 0},
	{muro3: 0},
	{correio2: 0},
	{correio3: 0},
	{lixeira_plastico: 0},
	{lixeira_metal: 0},
	{layout_hero: 0},
	{garrafa_quest: 0},
	{layout_desafios: 0},
	{lixeira_plastico_quest: 0},
	{Desafios: 0},
	{pontos: 0},
	{TiposDesafio: 0},
	{lixeira_metal_quest: 0},
	{latinha_quest: 0},
	{pontos_lata: 0},
	{pontos_salgadinho: 0},
	{salgadinho_quest: 0},
	{Projétil: 0},
	{flecha: 0},
	{fundo_inicio: 0},
	{Nome_jogo: 0},
	{jogar: 0},
	{Opções: 0},
	{TUTORIAL: 0},
	{Botão: 0},
	{ElementoHTML: 0},
	{Áudio: 0},
	{Sprite: 0},
	{bemVindo: 0},
	{Sprite2: 0},
	{teclas: 0},
	{Sprite3: 0},
	{objetivo_jogo: 0},
	{pegue_lixos: 0},
	{Voltar: 0},
	{Sprite4: 0},
	{Texto: 0},
	{Sprite5: 0},
	{VoltarMenu: 0},
	{Sprite6: 0},
	{VelocidadeEnemy: 0},
	{vidaHero: 0},
	{pontos_total: 0},
	{pontos_pet: 0},
	{pego_pet: 0},
	{pego_lata: 0},
	{pego_salgadinho: 0}
];

self.InstanceType = {
	praca1: class extends self.ISpriteInstance {},
	calcada: class extends self.ISpriteInstance {},
	predio: class extends self.ISpriteInstance {},
	trem2: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Hero: class extends self.ISpriteInstance {},
	Casa1: class extends self.ISpriteInstance {},
	grama: class extends self.ISpriteInstance {},
	rua2: class extends self.ISpriteInstance {},
	rua3: class extends self.ISpriteInstance {},
	neve1: class extends self.ISpriteInstance {},
	neve2: class extends self.ISpriteInstance {},
	neve3: class extends self.ISpriteInstance {},
	neve4: class extends self.ISpriteInstance {},
	deserto1: class extends self.ISpriteInstance {},
	deserto2: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	rua: class extends self.ISpriteInstance {},
	calcada1: class extends self.ISpriteInstance {},
	garrafa2: class extends self.ISpriteInstance {},
	salgadinho2: class extends self.ISpriteInstance {},
	latinha2: class extends self.ISpriteInstance {},
	calcada2: class extends self.ISpriteInstance {},
	pedra1: class extends self.ISpriteInstance {},
	pedra2: class extends self.ISpriteInstance {},
	poste1: class extends self.ISpriteInstance {},
	pedra4: class extends self.ISpriteInstance {},
	arvore1: class extends self.ISpriteInstance {},
	arvore2: class extends self.ISpriteInstance {},
	correio: class extends self.ISpriteInstance {},
	poste2: class extends self.ISpriteInstance {},
	pedra5: class extends self.ISpriteInstance {},
	arvore3: class extends self.ISpriteInstance {},
	arvore4: class extends self.ISpriteInstance {},
	pedra6: class extends self.ISpriteInstance {},
	pedra7: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	casa2: class extends self.ISpriteInstance {},
	casa3: class extends self.ISpriteInstance {},
	casa4: class extends self.ISpriteInstance {},
	muro2: class extends self.ISpriteInstance {},
	muro1: class extends self.ISpriteInstance {},
	rua1: class extends self.ISpriteInstance {},
	pedra8: class extends self.ISpriteInstance {},
	planta: class extends self.ISpriteInstance {},
	muro3: class extends self.ISpriteInstance {},
	correio2: class extends self.ISpriteInstance {},
	correio3: class extends self.ISpriteInstance {},
	lixeira_plastico: class extends self.ISpriteInstance {},
	lixeira_metal: class extends self.ISpriteInstance {},
	layout_hero: class extends self.ISpriteInstance {},
	garrafa_quest: class extends self.ISpriteInstance {},
	layout_desafios: class extends self.ISpriteInstance {},
	lixeira_plastico_quest: class extends self.ISpriteInstance {},
	Desafios: class extends self.ITextInstance {},
	pontos: class extends self.ITextInstance {},
	TiposDesafio: class extends self.ITextInstance {},
	lixeira_metal_quest: class extends self.ISpriteInstance {},
	latinha_quest: class extends self.ISpriteInstance {},
	pontos_lata: class extends self.ITextInstance {},
	pontos_salgadinho: class extends self.ITextInstance {},
	salgadinho_quest: class extends self.ISpriteInstance {},
	flecha: class extends self.ISpriteInstance {},
	fundo_inicio: class extends self.ISpriteInstance {},
	Nome_jogo: class extends self.ITextInstance {},
	jogar: class extends self.ITextInstance {},
	Opções: class extends self.ITextInstance {},
	TUTORIAL: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	ElementoHTML: class extends self.IHTMLElementInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bemVindo: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	teclas: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	objetivo_jogo: class extends self.ITextInstance {},
	pegue_lixos: class extends self.ITextInstance {},
	Voltar: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	VoltarMenu: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {}
}